#!/usr/bin/env bash
# Redirect a page
#sudo apt update -y
#sudo apt install nginx -y
#echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo service nginx stop
new_config="server_name \_\;\n\tlocation \/redirect_me \{\n\t\treturn 301 \$scheme\:\/\/\$http_host\;\n\t\}\n"
sudo sed -i "s/server_name _;/$new_config/" /etc/nginx/sites-enabled/default
sudo service nginx start
