#!/usr/bin/env bash
# Redirect a page
sudo apt update -y
sudo apt install nginx -y
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo service nginx stop
new_config="server_name \_\;\n\tlocation \/redirect_me \{\n\t\treturn 301 \$scheme\:\/\/\$http_host\;\n\t\}\n"
sudo sed -i "s/server_name _;/$new_config/" /etc/nginx/sites-enabled/default
replace="server_name \_\;"
change_404="server_name \_\;\n\n\terror_page 404 \@look_up\;\n\tlocation \@look_up \{\n\t\treturn 404 \"Ceci n\'est pas une page\\\n\\\n\"\;\n\t\}\n"
sudo sed -i "s/$replace/$change_404/" /etc/nginx/sites-enabled/default
sudo service nginx start
