#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt update -y
sudo apt install haproxy -y
echo "frontend main
	bind *:80
	default_backend servers

backend servers
	balance roundrobin
	server web-01 10.0.0.1:80 check
	server web-02 10.0.0.2:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo systemctl enable haproxy
sudo systemctl start haproxy
