#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt update -y
sudo apt install haproxy -y
echo "frontend main
	bind *:80
	default_backend servers

backend servers
	balance roundrobin
	server web-01 34.232.68.81:80 check
	server web-02 54.198.29.36:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo systemctl enable haproxy
sudo systemctl start haproxy
