#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it

date=$(date +%d-%m-%Y)
mysqldump --all-databases -u root --password="$1" > backup.sql
tar -zcvf "$date.tar.gz" backup.sql
echo "MySQL dump and compression completed"
