#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it

date=$(date +%d-%m-%Y)
mysqldump -u root -p "$1" --all-databases > backup.sql
tar -zcvf "$date.tar.gz" backup.sql
sudo rm backup.sql
echo "MySQL dump and compression completed"
