#!/usr/bin/env bash
# fetch datadog dashboard info

DD_API_KEY="da1a6b572b714ba2d43b45b8486bc25b"
DD_APP_KEY="bcfd122fc02258d360dfb1129141deb304cf34b1"

curl -X GET "https://api.datadoghq.com/api/v1/dashboard" \
-H "Accept: application/json" \
-H "DD-API-KEY: ${DD_API_KEY}" \
-H "DD-APPLICATION-KEY: ${DD_APP_KEY}"
