#!/usr/bin/env bash
# script does a lot of things
touch /var/run/myscript.pid
pid=$(pgrep -f ./var/run/myscript.pid)
echo "$pid"
trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?" SIGINT
trap 'kill -s 15 $pid; rm -r /var/run/myscript.pd' SIGQUIT SIGTERM
while true
do
	echo "To infinity and beyond"
done
