#!/usr/bin/env bash
# A script that displays "To infinity and beyond" indefinitely
count=1
trap "echo I am invincible!!!" SIGTERM
while [ $count ];
do
	echo "To infinity and beyond"
	sleep 2
	((count++))
done
