#!/usr/bin/env bash
# A script that displays "Best School" 10X and "Hi" @ the 9th time
count=0
while [ $count -lt 11 ];
do
	if [ "$count" -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((count++))
done
