#!/usr/bin/env bash
# script loops from 1 to 10, 4th "bad luck", 8th "good luck", others "Best School"
count=1
while [ $count -lt 11 ];
do
	if [ "$count" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$count" -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
