#!/usr/bin/env bash
# script loops from 1 to 20, echo different @ 4, 9 and 17
count=1
while [ $count -lt 21 ];
do
	case $count in 
		4)
			echo $count
			echo "bad luck from china"
			;;
		9)
			echo $count
			echo "bad luck from Japan"
			;;
		17)
			echo $count
			echo "bad luck from Italy"
			;;
		*)
			echo $count
			;;
	esac
	((count++))
done
